### ISSUE TITLE
New weapon

### ISSUE THREAD

**Issue by neyna** [NathalieWK/Combiner#1]
Hello,

do you plan to update it for the new weapon?

I see you opened a ticket for the discipline cell on the orignal author reposity so i am doing the same :)

Thanks in advance.

**Comment by NathalieWK** [comment]
Yep I do, just need to find the time for it at the moment.

**Comment by neyna** [comment]
Ok thanks. Nice to know :)

**Comment by neyna** [comment]
There is another website which is up to date : https://dauntlessbuildsearch.ml
Telling you that in case you don't want to keep maintaining this one.
